// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0IgcsliW3ju90FCpLdY8QqoZcvWNeTm8',
    appId: '1:2354700761:android:ef4a22a95c6cbc116eb9c8',
    messagingSenderId: '2354700761',
    projectId: 'jobmatch-r',
    databaseURL:
        'https://jobmatch-r-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'jobmatch-r.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS9Dos1kmou5f4PbL5-Zu5jNfNaJiO98s',
    appId: '1:2354700761:ios:85248d631f776a176eb9c8',
    messagingSenderId: '2354700761',
    projectId: 'jobmatch-r',
    databaseURL:
        'https://jobmatch-r-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'jobmatch-r.appspot.com',
    iosBundleId: 'com.romainfloriani.jobmatchr',
  );
}
